##******** SITE SETTINGS ********##

title: Andre Attamimi
tagline: Learn, Practice, Share and Grow
# The `>` after `description:` means to ignore line-breaks until next key.
# If you want to omit the line-break after the end of text, use `>-` instead.
description: &AUTHOR_BIO >
  I strongly believe in the importance of learning, practicing, sharing, and growing.
  I am also committed to doing this in my life, so that it benefits both myself and others.

## Global author, for multiple author see https://github.com/jekyll/jekyll-seo-tag/blob/master/docs/advanced-usage.md#author-information
author: &POST_AUTHOR
  name: Andre Attamimi
  email: rumatua0@gmail.com
  url: https://github.com/sionta
  twitter: &TWITTER R007MMXV
  bio: *AUTHOR_BIO
  #picture: /assets/img/logo.svg

## Default Image Settings
#logo: "/assets/img/logo.png" # Site logo
#image: "/assets/img/default.jpg" # Post image

## Language & Geographic Settings
lang: en
timezone: Asia/Tokyo

## Social & OG Settings
twitter:
  username: *TWITTER
  card: summary # summary, summary_large_image, app, player
social:
  <<: *POST_AUTHOR
  links:
    - https://x.com/R007MMXV
    - https://github.com/sionta
    - https://www.linkedin.com/in/andreattamimi

## Navigation
navigation:
  - index.html
  - blog/index.html
  - pages/about.md
  - pages/contact.md

## Pagination
#paginate: 12
#paginate_path: "/blog/page:num/"

## Site domain settings
baseurl: "" # the subpath of your site, e.g. /blog (no trailing slash)
url: "sionta-blog-test.netlify.app" # the base hostname & protocol, e.g. https://example.com (no trailing slash)

## Staticman settings
staticman:
  api: https://a2bb62c.up.railway.app # Staticman API (no trailing slash)
  repo: sionta/blog-test # username/repo
  branch: master

##******** BUILD SETTINGS ********##

jekyll-archives:
  layout: archive
  enabled:
    - categories
    - tags
  layouts:
    category: archive
    tag: archive
  permalinks:
    category: "/category/:name/"
    tag: "/tag/:name/"

defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: post
      permalink: "/blog/:title/"
      author:
        <<: *POST_AUTHOR

highlighter: rouge
markdown: kramdown
kramdown:
  input: GFM
  ## Table of contents
  toc_levels: 2..3
  auto_ids: true
  ## Syntax highlighting
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    css_class: highlight
    #block:
    #  line_numbers: true
    #  start_line: 1
    #span:
    #  line_numbers: false

sass:
  style: compressed
  sourcemap: development

exclude:
  - "*.gem"
  - "*.gemspec"
  - "script/"
  - "vendor/"
  - "node_modules/"
  - "package*.json"
  - "yarn.lock"
  - "vercel.json"
  - "netlify.toml"
  - "LICENSE"
  - "README.md"
  - "CODE_OF_CONDUCT.md"
